### ISSUE TITLE
[CRITICAL] Chatbot is breaking

### ISSUE THREAD

**Issue by rabi3daoudd** [rabi3daoudd/SyllabusSync#73]
Application error: a client-side exception has occurred (see the browser console for more information).

Error: Minified React error #301; visit https://react.dev/errors/301 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at rz (fd9d1056-6ebe52fb4ca6cda6.js:1:40583)
    at rE (fd9d1056-6ebe52fb4ca6cda6.js:1:40363)
    at l$ (fd9d1056-6ebe52fb4ca6cda6.js:1:59318)
    at iZ (fd9d1056-6ebe52fb4ca6cda6.js:1:117925)
    at ia (fd9d1056-6ebe52fb4ca6cda6.js:1:95164)
    at fd9d1056-6ebe52fb4ca6cda6.js:1:94986
    at il (fd9d1056-6ebe52fb4ca6cda6.js:1:94993)
    at oJ (fd9d1056-6ebe52fb4ca6cda6.js:1:92349)
    at nb (fd9d1056-6ebe52fb4ca6cda6.js:1:26835)
    at nw (fd9d1056-6ebe52fb4ca6cda6.js:1:27573)
window.console.error @ 23-ea47eee900bdf59f.js:1

**Comment by rabi3daoudd** [comment]
I may have a fix for this in this pull request: https://github.com/rabi3daoudd/SyllabusSync/pull/74
